name: Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # If you need to set up Node.js (optional for static sites)
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    # Install dependencies (if any)
    - name: Install dependencies
      run: npm ci
    
    # Simple build step
    - name: Build
      run: npm run build
    
    # Add deployment steps here (e.g., GitHub Pages deployment)